notARepository: 'quit'
git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: diff-so-fancy
os:
  editPreset: nvim
keybinding:
  files:
    commitChangesWithoutHook: <disabled>
customCommands:
  - key: w
    prompts:
      - type: input
        title: Commit summary
        initialValue: ''
    description: Commit changes without pre-commit hook
    command: git commit -n -m '{{index .PromptResponses 0}}'
    context: files
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
gui:
  mouseEvents: false
  showBottomLine: false
  theme:
    activeBorderColor:
      - magenta
    selectedLineBgColor:
      - black
    unstagedChangesColor:
      - yellow
  border: rounded
  nerdFontsVersion: '3'
